### PR TITLE
Pydantic 2.4 support

### PR DESCRIPTION
**Pull request by dannymeijer**
## Description
- Brings in support for pydantic 2.4
- Loosens dependencies a bit, making it easier to install along with other libraries
- Adds pylint and mypy sections to poetry configuration (pyproject.toml)
- ~~Disable apache-airflow (needs to be manually side loaded as poetry is unable to) - this because apache-airflow supports pydantic 2.*, but poetry's dependency resolced doesn't understand how to resolve it correctly~~
- no new tests needed
- ~~Black configuration modernized (120 character width vs 88)~~
## Related Issue
N/A

## Motivation and Context
Want to bring in support for pydantic 2.4

## How Has This Been Tested?
Unit tests and some integration tests with locally available projects that run against Brickflow

## Screenshots (if appropriate):
N/A

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] ~~My change requires a change to the documentation.~~
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by dannymeijer** [comment]
updates:
- [x] reversed the line length change for black (left pylint alone to avoid having to update a bunch of docstrings)
- [x] fixed apache-airflow dependency

**Review by asingamaneni — APPROVED** [review]
LGTM

**Comment by dannymeijer** [comment]
Please let me know when/if we can get a release around this PR. :)

**Comment by asingamaneni** [comment]
> Please let me know when/if we can get a release around this PR. :)

One more PR pending from @stikkireddy , as it gets fixed we can do 1.0.0. We can target next week

**Pull request merged**
